# Jesse PB
# 6/13/2022
# Using this script for Jess


# This script pulls in txt files output from gasmet both before and after an
# software update and converts them into a single dataframe that can be exported
# as a csv ready for analysis

# this script can be adjusted to change what outputs are extracted from the txt
# files

# this script is not elegant and hopefully will never need to be used again



# START

# copied txt files from 2020 assorted_txt_files

# manually remove duplicates in folder


# reading in txt files ----------------------------------------------------

getwd()

# The file generated by Calcmet when compiling the SPE files ends at "TXT"
# Therefore by making the pattern "txt" we are only pulling from text files that
# were not compiled (result output)

list.files("hr-expriment_gasmet-pull-request_20220525",
           pattern = "txt")


setwd("hr-expriment_gasmet-pull-request_20220525")
getwd()

fnames <- list.files(pattern = "txt")


shortdat <- data.frame(matrix(ncol = 8))
#Fill in the column names
colnames(shortdat) <-
  c("date", "CO2", "CH4", "N2O", "plot", "site", "experiment", "filename")


for (i in 1:length(fnames)) {
  #runs through all the files in the folder
  sdat <-
    read.table(
      paste(fnames[i]),
      header = T,
      stringsAsFactors = F,
      sep = "\t",
      fill = TRUE
    ) #opens the text files, Jesse added "fill=TRUE"
  if (colnames(sdat)[1] == "Line") {
    #The old files that were repredicted by the Gasmet folks have a strange format. This identifies those files by seeing if the first column is labeled "Line"
    sdat$date <-
      paste(sdat$Date, sdat$Time) #These files need to have two columns merged into one "time" column
    keepcols <-
      c(47, 10, 14, 18) #The time column and the gasses of interest are in these columns
    # 10 = CO2
    # 14 = Methane.CH4
    # 18 = N20,
    # 47 = date
    sdat <-
      sdat[, keepcols] #Here we drop all the other columns that are not of interest
  } else{
    keepcols <-
      c(1, 4, 6, 8) #This does the same thing, but for the files that were created with the updated gasmet equation
    sdat <- sdat[, keepcols]
  }
  colnames(sdat) <-
    c("date", "CO2", "CH4", "N2O") #rename those columns into something more simple
  sdat$plot <-
    str_split_fixed(fnames[1], " ", 5)[,4] 
  sdat$site <-
    str_split_fixed(fnames[1], " ", 5) [,3]
  sdat$experiment <- "eddyflux"
  sdat$filename <- fnames[i]
  # c((1:nrow(sdat) * 20) / 3600) #this is the "time" in fractions of an hour, since our final units will be in CO2e/m2/hour
  shortdat <- rbind(shortdat, sdat)
}
# removing first row and last column
shortdat %>% 
  slice(-1) -> dat_all


# reset wd
setwd("~/R projects/gasmet")

# rename column names
# rename factor levels
# add in same columns
# datetime, date, time, site, plot, co2, filename, n20, ch4, nh3, temp

dat_all %>%
  rename(datetime=date)  %>%
  # glimpse()
  mutate(datetime = as.POSIXct(datetime,
                               format = "%Y-%m-%d %H:%M:%S")) %>% 
  mutate(date = format(datetime,"%Y-%m-%d"),
         time = format(datetime, "%H:%M:%S"),
         .after=datetime) %>% 
  relocate(site,plot,.after=time) %>% 
  relocate(experiment,.after=N2O) %>% 
  rename(co2=CO2,
         ch4=CH4,
         n20 = N2O) %>% 
  write.csv("jess-hr-experiment_13Jun2022.csv",
            row.names = F)






















# group1 ------------------------------------------------------------------

## group1
# setwd("~/R projects/gasmet/2020_jul-oct_txt-for-jakek/agroup1")
# list.files()
# 
# # Jakes code detects and handles 2 different types of txt file generated by gasmet
# fnames<-grep("txt|TXT", list.files(), value=TRUE)

# empty dataframe
shortdat <- data.frame(matrix(ncol = 8))
#Fill in the column names
colnames(shortdat) <-
  c("date", "CO2", "CH4", "N2O", "plot", "site", "experiment", "filename")

# detect split points in filenames
# fnames[1]
# str_sub(fnames[1],end=-5)
# str_split_fixed(str_sub(fnames[1],end=-5), " ", 5)

for (i in 1:length(fnames)) {
  #runs through all the files in the folder
  sdat <-
    read.table(
      paste(fnames[i]),
      header = T,
      stringsAsFactors = F,
      sep = "\t",
      fill = TRUE
    ) #opens the text files, Jesse added "fill=TRUE"
  if (colnames(sdat)[1] == "Line") {
    #The old files that were repredicted by the Gasmet folks have a strange format. This identifies those files by seeing if the first column is labeled "Line"
    sdat$date <-
      paste(sdat$Date, sdat$Time) #These files need to have two columns merged into one "time" column
    keepcols <-
      c(47, 10, 14, 18) #The time column and the gasses of interest are in these columns
    # 10 = CO2
    # 14 = Methane.CH4
    # 18 = N20,
    # 47 = date
    sdat <-
      sdat[, keepcols] #Here we drop all the other columns that are not of interest
  } else{
    keepcols <-
      c(1, 4, 6, 8) #This does the same thing, but for the files that were created with the updated gasmet equation
    sdat <- sdat[, keepcols]
  }
  colnames(sdat) <-
    c("date", "CO2", "CH4", "N2O") #rename those columns into something more simple
  sdat$plot <-
    str_split_fixed(fnames[1], " ", 5)[,4] 
  sdat$site <-
    str_split_fixed(fnames[1], " ", 5) [,3]
  sdat$experiment <- "eddyflux"
  sdat$filename <- fnames[i]
  # c((1:nrow(sdat) * 20) / 3600) #this is the "time" in fractions of an hour, since our final units will be in CO2e/m2/hour
  shortdat <- rbind(shortdat, sdat)
}
# removing first row and last column
shortdat %>% 
  slice(-1)  -> agroup1


# group2 ------------------------------------------------------------------

## group2
setwd("~/R projects/gasmet/2020_jul-oct_txt-for-jakek/agroup2")
list.files()

# Jakes code detects and handles 2 different types of txt file generated by gasmet
fnames<-grep("txt|TXT", list.files(), value=TRUE)

# empty dataframe
shortdat <- data.frame(matrix(ncol = 8))
#Fill in the column names
colnames(shortdat) <-
  c("date", "CO2", "CH4", "N2O", "plot", "site", "experiment", "filename")

# detect split points in filenames
# fnames[1]
# str_sub(fnames[1],end=-5)
# str_split_fixed(str_sub(fnames[1],end=-5), " ", 5)

for (i in 1:length(fnames)) {
  #runs through all the files in the folder
  sdat <-
    read.table(
      paste(fnames[i]),
      header = T,
      stringsAsFactors = F,
      sep = "\t",
      fill = TRUE
    ) #opens the text files, Jesse added "fill=TRUE"
  if (colnames(sdat)[1] == "Line") {
    #The old files that were repredicted by the Gasmet folks have a strange format. This identifies those files by seeing if the first column is labeled "Line"
    sdat$date <-
      paste(sdat$Date, sdat$Time) #These files need to have two columns merged into one "time" column
    keepcols <-
      c(47, 10, 14, 18) #The time column and the gasses of interest are in these columns
    # 10 = CO2
    # 14 = Methane.CH4
    # 18 = N20,
    # 47 = date
    sdat <-
      sdat[, keepcols] #Here we drop all the other columns that are not of interest
  } else{
    keepcols <-
      c(1, 4, 6, 8) #This does the same thing, but for the files that were created with the updated gasmet equation
    sdat <- sdat[, keepcols]
  }
  colnames(sdat) <-
    c("date", "CO2", "CH4", "N2O") #rename those columns into something more simple
  sdat$plot <-
    str_split_fixed(str_sub(fnames[1],end=-5), " ", 5)[,4]
  sdat$site <-
    str_split_fixed(str_sub(fnames[1],end=-5), " ", 5)[,3]
  sdat$experiment <- "eddyflux"
  sdat$filename <- fnames[i]
  shortdat <- rbind(shortdat, sdat)
}
# removing first row
shortdat %>% 
  slice(-1)  -> agroup2

# group 3 -----------------------------------------------------------------

## group3
setwd("~/R projects/gasmet/2020_jul-oct_txt-for-jakek/agroup3")
list.files()

# Jakes code detects and handles 2 different types of txt file generated by gasmet
fnames<-grep("txt|TXT", list.files(), value=TRUE)

# empty dataframe
shortdat <- data.frame(matrix(ncol = 8))
#Fill in the column names
colnames(shortdat) <-
  c("date", "CO2", "CH4", "N2O", "plot", "site", "experiment", "filename")

# detect split points in filenames
# fnames[1]
# str_sub(fnames[1],end=-5)
# str_split_fixed(str_sub(fnames[1],end=-5), " ", 5)

for (i in 1:length(fnames)) {
  #runs through all the files in the folder
  sdat <-
    read.table(
      paste(fnames[i]),
      header = T,
      stringsAsFactors = F,
      sep = "\t",
      fill = TRUE
    ) #opens the text files, Jesse added "fill=TRUE"
  if (colnames(sdat)[1] == "Line") {
    #The old files that were repredicted by the Gasmet folks have a strange format. This identifies those files by seeing if the first column is labeled "Line"
    sdat$date <-
      paste(sdat$Date, sdat$Time) #These files need to have two columns merged into one "time" column
    keepcols <-
      c(47, 10, 14, 18) #The time column and the gasses of interest are in these columns
    # 10 = CO2
    # 14 = Methane.CH4
    # 18 = N20,
    # 47 = date
    sdat <-
      sdat[, keepcols] #Here we drop all the other columns that are not of interest
  } else{
    keepcols <-
      c(1, 4, 6, 8) #This does the same thing, but for the files that were created with the updated gasmet equation
    sdat <- sdat[, keepcols]
  }
  colnames(sdat) <-
    c("date", "CO2", "CH4", "N2O") #rename those columns into something more simple
  sdat$plot <-
    str_split_fixed(str_sub(fnames[1],end=-5), " ", 5)[,3]
  sdat$site <-
    str_split_fixed(str_sub(fnames[1],end=-5), " ", 5)[,2]
  sdat$experiment <- "eddyflux"
  sdat$filename <- fnames[i]
  shortdat <- rbind(shortdat, sdat) %>% 
    slice(-1) 
}
# removing first row and last column
shortdat -> agroup3


# group 4 -----------------------------------------------------------------

## group4
setwd("~/R projects/gasmet/2020_jul-oct_txt-for-jakek/agroup4")
list.files()

# Jakes code detects and handles 2 different types of txt file generated by gasmet
fnames<-grep("txt|TXT", list.files(), value=TRUE)

# empty dataframe
shortdat <- data.frame(matrix(ncol = 8))
#Fill in the column names
colnames(shortdat) <-
  c("date", "CO2", "CH4", "N2O", "plot", "site", "experiment", "filename")

# detect split points in filenames
# fnames[1]
# str_sub(fnames[1],end=-5)
# str_split_fixed(str_sub(fnames[1],end=-5), " ", 6)

for (i in 1:length(fnames)) {
  #runs through all the files in the folder
  sdat <-
    read.table(
      paste(fnames[i]),
      header = T,
      stringsAsFactors = F,
      sep = "\t",
      fill = TRUE
    ) #opens the text files, Jesse added "fill=TRUE"
  if (colnames(sdat)[1] == "Line") {
    #The old files that were repredicted by the Gasmet folks have a strange format. This identifies those files by seeing if the first column is labeled "Line"
    sdat$date <-
      paste(sdat$Date, sdat$Time) #These files need to have two columns merged into one "time" column
    keepcols <-
      c(47, 10, 14, 18) #The time column and the gasses of interest are in these columns
    # 10 = CO2
    # 14 = Methane.CH4
    # 18 = N20,
    # 47 = date
    sdat <-
      sdat[, keepcols] #Here we drop all the other columns that are not of interest
  } else{
    keepcols <-
      c(1, 4, 6, 8) #This does the same thing, but for the files that were created with the updated gasmet equation
    sdat <- sdat[, keepcols]
  }
  colnames(sdat) <-
    c("date", "CO2", "CH4", "N2O") #rename those columns into something more simple
  sdat$plot <-
    str_split_fixed(str_sub(fnames[1],end=-5), " ", 6)[,5]
  sdat$site <-
    str_split_fixed(str_sub(fnames[1],end=-5), " ", 6) [,4]
  sdat$experiment <- "eddyflux"
  sdat$filename <- fnames[i]
  shortdat <- rbind(shortdat, sdat) %>% 
    slice(-1) 
}
# removing first row and last column
shortdat -> agroup4


# group 5 -----------------------------------------------------------------
## group5
setwd("~/R projects/gasmet/2020_jul-oct_txt-for-jakek/agroup5")
list.files()

# Jakes code detects and handles 2 different types of txt file generated by gasmet
fnames<-grep("txt|TXT", list.files(), value=TRUE)

# empty dataframe
shortdat <- data.frame(matrix(ncol = 8))
#Fill in the column names
colnames(shortdat) <-
  c("date", "CO2", "CH4", "N2O", "plot", "site", "experiment", "filename")

# detect split points in filenames
# fnames[1]
# str_sub(fnames[1],end=-5)
# str_split_fixed(str_sub(fnames[1],end=-5), " ", 6)

for (i in 1:length(fnames)) {
  #runs through all the files in the folder
  sdat <-
    read.table(
      paste(fnames[i]),
      header = T,
      stringsAsFactors = F,
      sep = "\t",
      fill = TRUE
    ) #opens the text files, Jesse added "fill=TRUE"
  if (colnames(sdat)[1] == "Line") {
    #The old files that were repredicted by the Gasmet folks have a strange format. This identifies those files by seeing if the first column is labeled "Line"
    sdat$date <-
      paste(sdat$Date, sdat$Time) #These files need to have two columns merged into one "time" column
    keepcols <-
      c(47, 10, 14, 18) #The time column and the gasses of interest are in these columns
    # 10 = CO2
    # 14 = Methane.CH4
    # 18 = N20,
    # 47 = date
    sdat <-
      sdat[, keepcols] #Here we drop all the other columns that are not of interest
  } else{
    keepcols <-
      c(1, 4, 6, 8) #This does the same thing, but for the files that were created with the updated gasmet equation
    sdat <- sdat[, keepcols]
  }
  colnames(sdat) <-
    c("date", "CO2", "CH4", "N2O") #rename those columns into something more simple
  sdat$plot <-
    str_split_fixed(str_sub(fnames[1],end=-5), " ", 6)[,2]
  sdat$site <-
    str_split_fixed(str_sub(fnames[1],end=-5), " ", 6) [,1]
  sdat$experiment <- "eddyflux"
  sdat$filename <- fnames[i]
  # fnm    c((1:nrow(sdat) * 20) / 3600) #this is the "time" in fractions of an hour, since our final units will be in CO2e/m2/hour
  shortdat <- rbind(shortdat, sdat) 
}
# removing first row and last column
shortdat %>% 
  slice(-1) -> agroup5

# group 6 -----------------------------------------------------------------
## group6
setwd("~/R projects/gasmet/2020_jul-oct_txt-for-jakek/agroup6")
list.files()

# Jakes code detects and handles 2 different types of txt file generated by gasmet
fnames<-grep("txt|TXT", list.files(), value=TRUE)

# empty dataframe
shortdat <- data.frame(matrix(ncol = 8))
#Fill in the column names
colnames(shortdat) <-
  c("date", "CO2", "CH4", "N2O", "plot", "site", "experiment", "filename")

# detect split points in filenames
# fnames[1]
# str_sub(fnames[1],end=-5)
# str_split_fixed(str_sub(fnames[1],end=-5), " ", 6)

for (i in 1:length(fnames)) {
  #runs through all the files in the folder
  sdat <-
    read.table(
      paste(fnames[i]),
      header = T,
      stringsAsFactors = F,
      sep = "\t",
      fill = TRUE
    ) #opens the text files, Jesse added "fill=TRUE"
  if (colnames(sdat)[1] == "Line") {
    #The old files that were repredicted by the Gasmet folks have a strange format. This identifies those files by seeing if the first column is labeled "Line"
    sdat$date <-
      paste(sdat$Date, sdat$Time) #These files need to have two columns merged into one "time" column
    keepcols <-
      c(47, 10, 14, 18) #The time column and the gasses of interest are in these columns
    # 10 = CO2
    # 14 = Methane.CH4
    # 18 = N20,
    # 47 = date
    sdat <-
      sdat[, keepcols] #Here we drop all the other columns that are not of interest
  } else{
    keepcols <-
      c(1, 4, 6, 8) #This does the same thing, but for the files that were created with the updated gasmet equation
    sdat <- sdat[, keepcols]
  }
  colnames(sdat) <-
    c("date", "CO2", "CH4", "N2O") #rename those columns into something more simple
  sdat$plot <-
    str_split_fixed(str_sub(fnames[1],end=-5), " ", 6)[,3]
  sdat$site <-
    str_split_fixed(str_sub(fnames[1],end=-5), " ", 6) [,1]
  sdat$experiment <- "eddyflux"
  sdat$filename <- fnames[i]
  # c((1:nrow(sdat) * 20) / 3600) #this is the "time" in fractions of an hour, since our final units will be in CO2e/m2/hour
  shortdat <- rbind(shortdat, sdat) 
}
# removing first row and last column
shortdat %>% 
  slice(-1) -> agroup6

# group 7 -----------------------------------------------------------------

## group7
setwd("~/R projects/gasmet/2020_jul-oct_txt-for-jakek/agroup7")
list.files()

# Jakes code detects and handles 2 different types of txt file generated by gasmet
fnames<-grep("txt|TXT", list.files(), value=TRUE)

# empty dataframe
shortdat <- data.frame(matrix(ncol = 8))
#Fill in the column names
colnames(shortdat) <-
  c("date", "CO2", "CH4", "N2O", "plot", "site", "experiment", "filename")

# detect split points in filenames
# fnames[1]
# str_sub(fnames[1],end=-5)
# str_split_fixed(str_sub(fnames[1],end=-5), " ", 6)

for (i in 1:length(fnames)) {
  #runs through all the files in the folder
  sdat <-
    read.table(
      paste(fnames[i]),
      header = T,
      stringsAsFactors = F,
      sep = "\t",
      fill = TRUE
    ) #opens the text files, Jesse added "fill=TRUE"
  if (colnames(sdat)[1] == "Line") {
    #The old files that were repredicted by the Gasmet folks have a strange format. This identifies those files by seeing if the first column is labeled "Line"
    sdat$date <-
      paste(sdat$Date, sdat$Time) #These files need to have two columns merged into one "time" column
    keepcols <-
      c(47, 10, 14, 18) #The time column and the gasses of interest are in these columns
    # 10 = CO2
    # 14 = Methane.CH4
    # 18 = N20,
    # 47 = date
    sdat <-
      sdat[, keepcols] #Here we drop all the other columns that are not of interest
  } else{
    keepcols <-
      c(1, 4, 6, 8) #This does the same thing, but for the files that were created with the updated gasmet equation
    sdat <- sdat[, keepcols]
  }
  colnames(sdat) <-
    c("date", "CO2", "CH4", "N2O") #rename those columns into something more simple
  sdat$plot <-
    str_split_fixed(str_sub(fnames[1],end=-5), " ", 6)[,2]
  sdat$site <-
    str_split_fixed(str_sub(fnames[1],end=-5), " ", 6) [,1]
  sdat$experiment <- "eddyflux"
  sdat$filename <- fnames[i]
  # c((1:nrow(sdat) * 20) / 3600) #this is the "time" in fractions of an hour, since our final units will be in CO2e/m2/hour
  shortdat <- rbind(shortdat, sdat) 
}
# removing first row and last column
shortdat %>% 
  slice(-1)-> agroup7

# reset wd
setwd("~/R projects/gasmet")


# bind together -----------------------------------------------------------

rbind(agroup1,agroup2,
      agroup3,agroup4,
      agroup5,agroup6,
      agroup7) -> dat_all


# rename column names
# rename factor levels
# add in same columns
# datetime, date, time, site, plot, co2, filename, n20, ch4, nh3, temp

dat_all %>%
  rename(datetime=date)  %>%
  # glimpse()
  mutate(datetime = as.POSIXct(datetime,
                               format = "%Y-%m-%d %H:%M:%S")) %>% 
  mutate(date = format(datetime,"%Y-%m-%d"),
         time = format(datetime, "%H:%M:%S"),
         .after=datetime) %>% 
  relocate(site,plot,.after=time) %>% 
  relocate(experiment,.after=N2O) %>% 
  rename(co2=CO2,
         ch4=CH4,
         n20 = N2O) %>% 
  write.csv("eddyflux_txt-file-update_13Apr2022.csv",
            row.names = F)



